# Generated by Django 4.2.5 on 2023-10-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tiempo_ejecucion', models.BigIntegerField()),
                ('nodos', models.IntegerField()),
                ('matriz_adyacencias', models.TextField()),
                ('distancias', models.TextField()),
                ('grafo_imagen_b64', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafos.grafo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grafos.usuario')),
            ],
        ),
    ]
