# Generated by Django 4.2.5 on 2023-11-10 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0002_alter_usuariografo_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariografo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
