# Generated by Django 4.2.5 on 2023-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0003_usuariografo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafo',
            name='tiempo_ejecucion',
            field=models.FloatField(),
        ),
    ]
