# Generated by Django 4.2.5 on 2023-11-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0004_alter_grafo_tiempo_ejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariografo',
            name='grafica_tiempos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
