# Generated by Django 4.2.5 on 2023-11-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafos', '0005_usuariografo_grafica_tiempos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafo',
            name='aristas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
